### ISSUE TITLE
MQTT clean session flag

### ISSUE THREAD

**Issue by tve** [EcmaTC53/spec#37]
The MQTT 3.1.0 standard includes a "clean session" flag in the connect message. I do not see this as an option in the proposed ECMA-419 MQTT class. Has this been left off intentionally?

**Comment by phoddie** [comment]
Looks like an oversight in the draft. the `clean` flag is an option in the Moddable SDK [mqttClient](https://github.com/Moddable-OpenSource/moddable/blob/819c387912fe0d8b53582b27c5739f1c261c3688/examples/io/tcp/mqttclient/mqttclient.js#L69) implementation that is used to test the standard.

**Comment by phoddie** [comment]
Addressed in the current draft spec
